WIP

diff --git a/bin/performance-test b/bin/performance-test
--- a/bin/performance-test
+++ b/bin/performance-test
@@ -29,6 +29,15 @@ function build_shade_jar() {
   fi
 }
 
+log4j_config="$at_home/conf/log4j.properties"
+if [ ! -f "$log4j_config" ]; then
+  log4j_config="$at_home/conf/log4j.properties.example"
+  if [ ! -f "$log4j_config" ]; then
+    echo "Could not find logj4.properties or log4j.properties.example in $at_home/conf"
+    exit 1
+  fi
+fi
+
 # TODO need to check if cluster-control.sh exists
 . $at_home/conf/cluster-control.sh
 build_shade_jar
